name: Build RPM Containers
description: |
  Builds the RPM-based containers.

runs:
  using: "composite"

  steps:

    - name: Build RPM containers
      shell: bash
      run: ./docker_rpm_build.py --rebuild --no-update-check
