name: Build Debian Containers
description: |
  Builds the Debian-based containers (noble, questing, resolute, trixie, sid).

runs:
  using: "composite"

  steps:

    - name: Build all Debian containers
      shell: bash
      run: ./docker_deb_build.py --rebuild --no-update-check
